repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.12
    hooks:
      - id: terraform-fmt
      - id: tflint
      - id: goimports
      - id: golint
      - id: markdown-link-check
      # - id: terraform-validate
      # - id: terragrunt-hclfmt
      # - id: shellcheck
      # - id: gofmt
      # - id: yapf
      # - id: helmlint
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.48.0
    hooks:
      - id: terraform_tfsec
      # - id: terraform_docs
